'use strict';

angular.module('attentiaPronostiekApp', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngRoute',
    'pascalprecht.translate'
  ])
  .config(function ($routeProvider) {
    $routeProvider
      .when('/', {
        templateUrl: 'views/main.html',
        controller: 'MainCtrl'
        }).when('/home', {
            templateUrl: 'views/main.html',
            controller: 'MainCtrl'
        }).when('/wedstrijdreglement', {
            templateUrl: 'views/wedstrijdreglement.html',
            controller: 'WedstrijdreglementCtrl'
        })
        .when('/mijnpronostiek', {
            templateUrl: 'views/userpronostiek.html',
            controller: 'PronostiekCtrl'
        }).when('/logout', {
            templateUrl: 'views/logout.html',
            controller: 'LogoutCtrl'
        }).when('/resultaten', {
            templateUrl: 'views/resultaten.html',
            controller: 'ResultatenCtrl'
        }).otherwise({
        redirectTo: '/views/main.html'
      })}).config(function($translateProvider){
                    $translateProvider.translations(
                        'fr',
                        {
                            'HOME': 'Accueil',
                            'WEDSTRIJDREGLEMENT': 'Règlement du concours',
                            'MIJNPRONOSTIEK': 'Mon pronostique',
                            'LOGOUT': 'Déconnexion',
                            'WACHTWOORD': 'Mot de passe',
                            'EMAIL': 'E-mail',
                            'BESTAANDEGEBRUIKER': 'Se connecter en tant qu’utilisateur existant',
                            'NAAM' : 'Nom',
                            'VOORNAAM': 'Prénom',
                            'KIESBU': 'Choisir votre business-unit',
                            'NIEUWEGEBRUIKER': 'S’enregistrer en tant que nouvel utilisateur',
                            'WERELDBEKERAPP': 'App pronostique Coupe du monde',
                            'EMAILATT': 'usager@attentia.be',
                            'NEMAILATT': 'nouveau.usager@attentia.be',
                            'VORIGE_PRONOSTIEKEN': 'Pronostiques précédents',
                            'groep A': 'Groupe A',
                            'groep B': 'Groupe B',
                            'groep C': 'Groupe C',
                            'groep D': 'Groupe D',
                            'groep E': 'Groupe E',
                            'groep F': 'Groupe F',
                            'groep G': 'Groupe G',
                            'groep H': 'Groupe H',
                            'Brazillië': 'Brésil',
                            'Kroatië': 'Croatie',
                            'Mexico': 'Mexique',
                            'Kameroen': 'Cameroun',
                            'Spanje': 'Espagne',
                            'Nederland': 'Hollande',
                            'Chili': 'Chili',
                            'Australië': 'Australie',
                            'Colombia': 'Colombie',
                            'Griekenland': 'Grèce',
                            'Ivoorkust': 'Côte d`Ivoire',
                            'Japan': 'Japon',
                            'Uruguay': 'Uruguay',
                            'Costa Rica': 'Costa Rica',
                            'Engeland': 'Angleterre',
                            'Italië': 'Italie',
                            'Zwitserland': 'Suisse',
                            'Ecuador': 'Equateur',
                            'Frankrijk': 'France',
                            'Honduras': 'Honduras',
                            'Argentinië': 'Argentine',
                            'Bosnië-Herzegovina': 'Bosnie-Herzégovine',
                            'Iran': 'Iran',
                            'Nigeria': 'Nigéria',
                            'Duitsland': 'Allemagne',
                            'Portugal': 'Portugal',
                            'Ghana': 'Ghana',
                            'Verenigde Staten': 'Etats-Unis',
                            'België': 'Belgique',
                            'Algerije': 'Algérie',
                            'Rusland': 'Russie',
                            'Zuid-Korea': 'Corée du Sud',
                            'WIEWINT': 'Qu’est-ce-qui va gagner la coupe du monde?',
                            'PRONOSTIEK_OPSLAAN': 'Enregistrer mon pronostique',
                            'UITGELOGD': 'Vous êtes déconnecté',
                            'Attentia corporate': 'Attentia corporate',
                            'Attentia sociaal secretariaat': 'Attentia secretariat social',
                            'Attentia kinderbijslag': 'Attentia allocations familiales',
                            'Attentia preventie & bescherming': 'Attentia allocations familiales',
                            'Attentia sociaal verzekeringsfonds': 'Attentia cas',
                            'Attentia nv - IT consulting': 'Attentia sa - IT consulting',
                            'Attentia nv - P&O consulting': 'Attentia sa - P&O consulting'
                        })
                        $translateProvider.translations('nl',
                        {   'HOME': 'Home',
                            'WEDSTRIJDREGLEMENT': 'Wedstrijdreglement',
                            'MIJNPRONOSTIEK': 'Mijn pronostiek',
                            'LOGOUT': 'Uitloggen',
                            'WACHTWOORD': 'Wachtwoord',
                            'EMAIL': 'E-mail',
                            'BESTAANDEGEBRUIKER': 'Inloggen als bestaande gebruiker',
                            'NAAM' : 'Naam',
                            'VOORNAAM': 'Voornaam',
                            'KIESBU': 'Kies je business-unit',
                            'NIEUWEGEBRUIKER': 'Registreren als nieuwe gebruiker',
                            'WERELDBEKERAPP': 'WK pronostiek app',
                            'EMAILATT': 'gebruiker@attentia.be',
                            'NEMAILATT': 'nieuwe.gebruiker@attentia.be',
                            'VORIGE_PRONOSTIEKEN': 'Vorige pronostieken',
                            'groep A': 'Groep A',
                            'groep B': 'Groep B',
                            'groep C': 'Groep C',
                            'groep D': 'Groep D',
                            'groep E': 'Groep E',
                            'groep F': 'Groep F',
                            'groep G': 'Groep G',
                            'groep H': 'Groep H',
                            'Brazillië': 'Brazillië',
                            'Kroatië': 'Kroatië',
                            'Mexico': 'Mexico',
                            'Kameroen': 'Kameroen',
                            'Spanje': 'Spanje',
                            'Nederland': 'Nederland',
                            'Chili': 'Chili',
                            'Australië': 'Australië',
                            'Colombia': 'Colombia',
                            'Griekenland': 'Griekenland',
                            'Ivoorkust': 'Ivoorkust',
                            'Japan': 'Japan',
                            'Uruguay': 'Uruguay',
                            'Costa Rica': 'Costa Rica',
                            'Engeland': 'Engeland',
                            'Italië': 'Italië',
                            'Zwitserland': 'Zwitserland',
                            'Ecuador': 'Ecuador',
                            'Frankrijk': 'Frankrijk',
                            'Honduras': 'Honduras',
                            'Argentinië': 'Argentinië',
                            'Bosnië-Herzegovina': 'Bosnië-Herzegovina',
                            'Iran': 'Iran',
                            'Nigeria': 'Nigeria',
                            'Duitsland': 'Duitsland',
                            'Portugal': 'Portugal',
                            'Ghana': 'Ghana',
                            'Verenigde Staten': 'Verenigde Staten',
                            'België': 'België',
                            'Algerije': 'Algerije',
                            'Rusland': 'Rusland',
                            'Zuid-Korea': 'Zuid-Korea',
                            'WIEWINT': 'Wie wint het WK?',
                            'PRONOSTIEK_OPSLAAN': 'Mijn pronostiek opslaan',
                            'UITGELOGD': 'Je bent afgemeld',
                            'Attentia corporate': 'Attentia corporate',
                            'Attentia sociaal secretariaat': 'Attentia sociaal secretariaat',
                            'Attentia kinderbijslag': 'Attentia kinderbijslag',
                            'Attentia preventie & bescherming': 'Attentia preventie & bescherming',
                            'Attentia sociaal verzekeringsfonds': 'Attentia sociaal verzekeringsfonds',
                            'Attentia nv - IT consulting': 'Attentia nv - IT consulting',
                            'Attentia nv - P&O consulting': 'Attentia nv - P&O consulting'});

            $translateProvider.preferredLanguage('nl');

});